<?xml version="1.0" encoding="UTF-8" ?>
<Package name="decos_goodbyeApp" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
        <BehaviorDescription name="behavior" src="animations/byebyewave" xar="behavior.xar" />
        <BehaviorDescription name="behavior" src="animations/pointright" xar="behavior.xar" />
        <BehaviorDescription name="behavior" src="animations/left_wave" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs>
        <Dialog name="chitchat" src="chitchat/chitchat.dlg" />
        <Dialog name="thanks-welcome" src="thanks-welcome/thanks-welcome.dlg" />
    </Dialogs>
    <Resources>
        <File name="tmp" src="tmp.txt" />
        <File name="barcode-help" src="html/common/barcode-help.html" />
        <File name="barcode" src="html/common/barcode.html" />
        <File name="bullet-questions-v2" src="html/common/bullet-questions-v2.html" />
        <File name="bullet-questions" src="html/common/bullet-questions.html" />
        <File name="code-v2" src="html/common/code-v2.html" />
        <File name="code" src="html/common/code.html" />
        <File name="displaydata" src="html/common/displaydata.html" />
        <File name="qminder" src="html/common/qminder.html" />
        <File name="question" src="html/common/question.html" />
        <File name="rate-interaction" src="html/common/rate-interaction.html" />
        <File name="scheduling_ask-v2" src="html/common/scheduling_ask-v2.html" />
        <File name="scheduling_ask-v3" src="html/common/scheduling_ask-v3.html" />
        <File name="scheduling_ask" src="html/common/scheduling_ask.html" />
        <File name="scheduling_result" src="html/common/scheduling_result.html" />
        <File name="scheduling_result_v2" src="html/common/scheduling_result_v2.html" />
        <File name="take_picture" src="html/common/take_picture.html" />
        <File name="welcome" src="html/common/welcome.html" />
        <File name="jqmobile" src="html/common/includes/jqmobile.js" />
        <File name="jqmobile" src="html/common/includes/jqmobile.js~" />
        <File name="jquery" src="html/common/includes/jquery.js" />
        <File name="jquery" src="html/common/includes/jquery.js~" />
        <File name="HELP-US-OUT" src="html/common/includes/font-awesome/HELP-US-OUT.txt" />
        <File name="font-awesome" src="html/common/includes/font-awesome/css/font-awesome.css" />
        <File name="font-awesome.min" src="html/common/includes/font-awesome/css/font-awesome.min.css" />
        <File name="fontawesome-webfont" src="html/common/includes/font-awesome/fonts/fontawesome-webfont.eot" />
        <File name="fontawesome-webfont" src="html/common/includes/font-awesome/fonts/fontawesome-webfont.svg" />
        <File name="fontawesome-webfont" src="html/common/includes/font-awesome/fonts/fontawesome-webfont.ttf" />
        <File name="fontawesome-webfont" src="html/common/includes/font-awesome/fonts/fontawesome-webfont.woff" />
        <File name="fontawesome-webfont" src="html/common/includes/font-awesome/fonts/fontawesome-webfont.woff2" />
        <File name="FontAwesome" src="html/common/includes/font-awesome/fonts/FontAwesome.otf" />
        <File name="animated" src="html/common/includes/font-awesome/less/animated.less" />
        <File name="bordered-pulled" src="html/common/includes/font-awesome/less/bordered-pulled.less" />
        <File name="core" src="html/common/includes/font-awesome/less/core.less" />
        <File name="fixed-width" src="html/common/includes/font-awesome/less/fixed-width.less" />
        <File name="font-awesome" src="html/common/includes/font-awesome/less/font-awesome.less" />
        <File name="icons" src="html/common/includes/font-awesome/less/icons.less" />
        <File name="larger" src="html/common/includes/font-awesome/less/larger.less" />
        <File name="list" src="html/common/includes/font-awesome/less/list.less" />
        <File name="mixins" src="html/common/includes/font-awesome/less/mixins.less" />
        <File name="path" src="html/common/includes/font-awesome/less/path.less" />
        <File name="rotated-flipped" src="html/common/includes/font-awesome/less/rotated-flipped.less" />
        <File name="screen-reader" src="html/common/includes/font-awesome/less/screen-reader.less" />
        <File name="stacked" src="html/common/includes/font-awesome/less/stacked.less" />
        <File name="variables" src="html/common/includes/font-awesome/less/variables.less" />
        <File name="_animated" src="html/common/includes/font-awesome/scss/_animated.scss" />
        <File name="_bordered-pulled" src="html/common/includes/font-awesome/scss/_bordered-pulled.scss" />
        <File name="_core" src="html/common/includes/font-awesome/scss/_core.scss" />
        <File name="_fixed-width" src="html/common/includes/font-awesome/scss/_fixed-width.scss" />
        <File name="_icons" src="html/common/includes/font-awesome/scss/_icons.scss" />
        <File name="_larger" src="html/common/includes/font-awesome/scss/_larger.scss" />
        <File name="_list" src="html/common/includes/font-awesome/scss/_list.scss" />
        <File name="_mixins" src="html/common/includes/font-awesome/scss/_mixins.scss" />
        <File name="_path" src="html/common/includes/font-awesome/scss/_path.scss" />
        <File name="_rotated-flipped" src="html/common/includes/font-awesome/scss/_rotated-flipped.scss" />
        <File name="_screen-reader" src="html/common/includes/font-awesome/scss/_screen-reader.scss" />
        <File name="_stacked" src="html/common/includes/font-awesome/scss/_stacked.scss" />
        <File name="_variables" src="html/common/includes/font-awesome/scss/_variables.scss" />
        <File name="font-awesome" src="html/common/includes/font-awesome/scss/font-awesome.scss" />
        <File name="buttonclick" src="html/common/scripts/buttonclick.js" />
        <File name="naoqi" src="html/common/scripts/naoqi.js" />
        <File name="resetbutton" src="html/common/scripts/resetbutton.js~" />
        <File name="dialog_example" src="dialog_example.py" />
        <File name="qimessaging" src="html/common/scripts/qimessaging.js" />
        <File name="ask_name" src="ask_name.tmp" />
        <File name="newResetButton" src="html/common/scripts/newResetButton.js" />
        <File name="jqmobile" src="html/common/includes/jqmobile.css" />
        <File name="display_data" src="html/common/modules/Display_Data/display_data.html" />
        <File name="style" src="html/common/modules/Display_Data/style.css" />
        <File name="style" src="html/common/modules/Menu/style.css" />
        <File name="__init__" src="lib/socketIO_client/__init__.py" />
        <File name="exceptions" src="lib/socketIO_client/exceptions.py" />
        <File name="heartbeats" src="lib/socketIO_client/heartbeats.py" />
        <File name="logs" src="lib/socketIO_client/logs.py" />
        <File name="namespaces" src="lib/socketIO_client/namespaces.py" />
        <File name="parsers" src="lib/socketIO_client/parsers.py" />
        <File name="six" src="lib/socketIO_client/six.py" />
        <File name="symmetries" src="lib/socketIO_client/symmetries.py" />
        <File name="transports" src="lib/socketIO_client/transports.py" />
        <File name="__init__" src="lib/socketIO_client/tests/__init__.py" />
        <File name="index" src="lib/socketIO_client/tests/index.html" />
        <File name="package" src="lib/socketIO_client/tests/package.json" />
        <File name="proxy" src="lib/socketIO_client/tests/proxy.js" />
        <File name="serve" src="lib/socketIO_client/tests/serve.js" />
        <File name="ssl" src="lib/socketIO_client/tests/ssl.crt" />
        <File name="ssl" src="lib/socketIO_client/tests/ssl.key" />
        <File name="__init__" src="lib/websocket/__init__.py" />
        <File name="_abnf" src="lib/websocket/_abnf.py" />
        <File name="_app" src="lib/websocket/_app.py" />
        <File name="_core" src="lib/websocket/_core.py" />
        <File name="_exceptions" src="lib/websocket/_exceptions.py" />
        <File name="_handshake" src="lib/websocket/_handshake.py" />
        <File name="_http" src="lib/websocket/_http.py" />
        <File name="_logging" src="lib/websocket/_logging.py" />
        <File name="_socket" src="lib/websocket/_socket.py" />
        <File name="_ssl_compat" src="lib/websocket/_ssl_compat.py" />
        <File name="_url" src="lib/websocket/_url.py" />
        <File name="_utils" src="lib/websocket/_utils.py" />
        <File name="cacert" src="lib/websocket/cacert.pem" />
        <File name="six" src="lib/websocket/six.py" />
        <File name="__init__" src="lib/websocket/tests/__init__.py" />
        <File name="test_websocket" src="lib/websocket/tests/test_websocket.py" />
        <File name="header01" src="lib/websocket/tests/data/header01.txt" />
        <File name="header02" src="lib/websocket/tests/data/header02.txt" />
        <File name="common" src="html/common/modules/common.css" />
        <File name="enu" src="Translate/enu.json" />
        <File name="dun" src="chitchat/dun.json" />
        <File name="dun" src="Translate/dun.json" />
        <File name="menu-v2" src="html/common/modules/Menu/menu-v2.html" />
        <File name="LICENSE" src="html/common/includes/materialize/LICENSE" />
        <File name="README" src="html/common/includes/materialize/README.md" />
        <File name="materialize" src="html/common/includes/materialize/css/materialize.css" />
        <File name="materialize.min" src="html/common/includes/materialize/css/materialize.min.css" />
        <File name="Roboto-Bold" src="html/common/includes/materialize/fonts/roboto/Roboto-Bold.eot" />
        <File name="Roboto-Bold" src="html/common/includes/materialize/fonts/roboto/Roboto-Bold.ttf" />
        <File name="Roboto-Bold" src="html/common/includes/materialize/fonts/roboto/Roboto-Bold.woff" />
        <File name="Roboto-Bold" src="html/common/includes/materialize/fonts/roboto/Roboto-Bold.woff2" />
        <File name="Roboto-Light" src="html/common/includes/materialize/fonts/roboto/Roboto-Light.eot" />
        <File name="Roboto-Light" src="html/common/includes/materialize/fonts/roboto/Roboto-Light.ttf" />
        <File name="Roboto-Light" src="html/common/includes/materialize/fonts/roboto/Roboto-Light.woff" />
        <File name="Roboto-Light" src="html/common/includes/materialize/fonts/roboto/Roboto-Light.woff2" />
        <File name="Roboto-Medium" src="html/common/includes/materialize/fonts/roboto/Roboto-Medium.eot" />
        <File name="Roboto-Medium" src="html/common/includes/materialize/fonts/roboto/Roboto-Medium.ttf" />
        <File name="Roboto-Medium" src="html/common/includes/materialize/fonts/roboto/Roboto-Medium.woff" />
        <File name="Roboto-Medium" src="html/common/includes/materialize/fonts/roboto/Roboto-Medium.woff2" />
        <File name="Roboto-Regular" src="html/common/includes/materialize/fonts/roboto/Roboto-Regular.eot" />
        <File name="Roboto-Regular" src="html/common/includes/materialize/fonts/roboto/Roboto-Regular.ttf" />
        <File name="Roboto-Regular" src="html/common/includes/materialize/fonts/roboto/Roboto-Regular.woff" />
        <File name="Roboto-Regular" src="html/common/includes/materialize/fonts/roboto/Roboto-Regular.woff2" />
        <File name="Roboto-Thin" src="html/common/includes/materialize/fonts/roboto/Roboto-Thin.eot" />
        <File name="Roboto-Thin" src="html/common/includes/materialize/fonts/roboto/Roboto-Thin.ttf" />
        <File name="Roboto-Thin" src="html/common/includes/materialize/fonts/roboto/Roboto-Thin.woff" />
        <File name="Roboto-Thin" src="html/common/includes/materialize/fonts/roboto/Roboto-Thin.woff2" />
        <File name="materialize" src="html/common/includes/materialize/js/materialize.js" />
        <File name="materialize.min" src="html/common/includes/materialize/js/materialize.min.js" />
        <File name="HISTORY" src="lib/socketIO_client/tests/node_modules/accepts/HISTORY.md" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/accepts/LICENSE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/accepts/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/accepts/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/accepts/package.json" />
        <File name="LICENCE" src="lib/socketIO_client/tests/node_modules/after/LICENCE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/after/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/after/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/after/package.json" />
        <File name="after-test" src="lib/socketIO_client/tests/node_modules/after/test/after-test.js" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/ansi-regex/index.js" />
        <File name="license" src="lib/socketIO_client/tests/node_modules/ansi-regex/license" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/ansi-regex/package.json" />
        <File name="readme" src="lib/socketIO_client/tests/node_modules/ansi-regex/readme.md" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/arraybuffer.slice/Makefile" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/arraybuffer.slice/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/arraybuffer.slice/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/arraybuffer.slice/package.json" />
        <File name="slice-buffer" src="lib/socketIO_client/tests/node_modules/arraybuffer.slice/test/slice-buffer.js" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/backo2/History.md" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/backo2/Makefile" />
        <File name="Readme" src="lib/socketIO_client/tests/node_modules/backo2/Readme.md" />
        <File name="component" src="lib/socketIO_client/tests/node_modules/backo2/component.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/backo2/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/backo2/package.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/backo2/test/index.js" />
        <File name="LICENSE-MIT" src="lib/socketIO_client/tests/node_modules/base64-arraybuffer/LICENSE-MIT" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/base64-arraybuffer/README.md" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/base64-arraybuffer/README.md~" />
        <File name="grunt" src="lib/socketIO_client/tests/node_modules/base64-arraybuffer/grunt.js" />
        <File name="base64-arraybuffer" src="lib/socketIO_client/tests/node_modules/base64-arraybuffer/lib/base64-arraybuffer.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/base64-arraybuffer/package.json" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/base64-arraybuffer/package.json~" />
        <File name="base64-arraybuffer_test" src="lib/socketIO_client/tests/node_modules/base64-arraybuffer/test/base64-arraybuffer_test.js" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/base64id/README.md" />
        <File name="base64id" src="lib/socketIO_client/tests/node_modules/base64id/lib/base64id.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/base64id/package.json" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/benchmark/LICENSE.txt" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/benchmark/README.md" />
        <File name="benchmark" src="lib/socketIO_client/tests/node_modules/benchmark/benchmark.js" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/benchmark/doc/README.md" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/benchmark/package.json" />
        <File name="run-test" src="lib/socketIO_client/tests/node_modules/benchmark/test/run-test.sh" />
        <File name="test" src="lib/socketIO_client/tests/node_modules/benchmark/test/test.js" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/better-assert/History.md" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/better-assert/Makefile" />
        <File name="Readme" src="lib/socketIO_client/tests/node_modules/better-assert/Readme.md" />
        <File name="example" src="lib/socketIO_client/tests/node_modules/better-assert/example.js" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/better-assert/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/better-assert/package.json" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/blob/Makefile" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/blob/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/blob/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/blob/package.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/blob/test/index.js" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/callsite/History.md" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/callsite/Makefile" />
        <File name="Readme" src="lib/socketIO_client/tests/node_modules/callsite/Readme.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/callsite/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/callsite/package.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/camelcase/index.js" />
        <File name="license" src="lib/socketIO_client/tests/node_modules/camelcase/license" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/camelcase/package.json" />
        <File name="readme" src="lib/socketIO_client/tests/node_modules/camelcase/readme.md" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/cliui/LICENSE.txt" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/cliui/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/cliui/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/cliui/package.json" />
        <File name="screenshot" src="lib/socketIO_client/tests/node_modules/cliui/screenshot.png" />
        <File name="cliui" src="lib/socketIO_client/tests/node_modules/cliui/test/cliui.js" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/code-point-at/index.js" />
        <File name="license" src="lib/socketIO_client/tests/node_modules/code-point-at/license" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/code-point-at/package.json" />
        <File name="readme" src="lib/socketIO_client/tests/node_modules/code-point-at/readme.md" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/component-bind/History.md" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/component-bind/Makefile" />
        <File name="Readme" src="lib/socketIO_client/tests/node_modules/component-bind/Readme.md" />
        <File name="component" src="lib/socketIO_client/tests/node_modules/component-bind/component.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/component-bind/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/component-bind/package.json" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/component-emitter/History.md" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/component-emitter/Makefile" />
        <File name="Readme" src="lib/socketIO_client/tests/node_modules/component-emitter/Readme.md" />
        <File name="bower" src="lib/socketIO_client/tests/node_modules/component-emitter/bower.json" />
        <File name="component" src="lib/socketIO_client/tests/node_modules/component-emitter/component.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/component-emitter/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/component-emitter/package.json" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/component-inherit/History.md" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/component-inherit/Makefile" />
        <File name="Readme" src="lib/socketIO_client/tests/node_modules/component-inherit/Readme.md" />
        <File name="component" src="lib/socketIO_client/tests/node_modules/component-inherit/component.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/component-inherit/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/component-inherit/package.json" />
        <File name="inherit" src="lib/socketIO_client/tests/node_modules/component-inherit/test/inherit.js" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/debug/History.md" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/debug/Makefile" />
        <File name="Readme" src="lib/socketIO_client/tests/node_modules/debug/Readme.md" />
        <File name="bower" src="lib/socketIO_client/tests/node_modules/debug/bower.json" />
        <File name="browser" src="lib/socketIO_client/tests/node_modules/debug/browser.js" />
        <File name="component" src="lib/socketIO_client/tests/node_modules/debug/component.json" />
        <File name="debug" src="lib/socketIO_client/tests/node_modules/debug/debug.js" />
        <File name="node" src="lib/socketIO_client/tests/node_modules/debug/node.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/debug/package.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/decamelize/index.js" />
        <File name="license" src="lib/socketIO_client/tests/node_modules/decamelize/license" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/decamelize/package.json" />
        <File name="readme" src="lib/socketIO_client/tests/node_modules/decamelize/readme.md" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/engine.io-client/History.md" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/engine.io-client/LICENSE" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/engine.io-client/Makefile" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/engine.io-client/README.md" />
        <File name="engine.io" src="lib/socketIO_client/tests/node_modules/engine.io-client/engine.io.js" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/engine.io-client/index.js" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/engine.io-client/lib/index.js" />
        <File name="socket" src="lib/socketIO_client/tests/node_modules/engine.io-client/lib/socket.js" />
        <File name="transport" src="lib/socketIO_client/tests/node_modules/engine.io-client/lib/transport.js" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/engine.io-client/lib/transports/index.js" />
        <File name="polling-jsonp" src="lib/socketIO_client/tests/node_modules/engine.io-client/lib/transports/polling-jsonp.js" />
        <File name="polling-xhr" src="lib/socketIO_client/tests/node_modules/engine.io-client/lib/transports/polling-xhr.js" />
        <File name="polling" src="lib/socketIO_client/tests/node_modules/engine.io-client/lib/transports/polling.js" />
        <File name="websocket" src="lib/socketIO_client/tests/node_modules/engine.io-client/lib/transports/websocket.js" />
        <File name="xmlhttprequest" src="lib/socketIO_client/tests/node_modules/engine.io-client/lib/xmlhttprequest.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/engine.io-client/package.json" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/engine.io-parser/History.md" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/engine.io-parser/LICENSE" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/engine.io-parser/Makefile" />
        <File name="Readme" src="lib/socketIO_client/tests/node_modules/engine.io-parser/Readme.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/engine.io-parser/index.js" />
        <File name="browser" src="lib/socketIO_client/tests/node_modules/engine.io-parser/lib/browser.js" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/engine.io-parser/lib/index.js" />
        <File name="keys" src="lib/socketIO_client/tests/node_modules/engine.io-parser/lib/keys.js" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/engine.io-parser/node_modules/has-binary/History.md" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/engine.io-parser/node_modules/has-binary/LICENSE" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/engine.io-parser/node_modules/has-binary/Makefile" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/engine.io-parser/node_modules/has-binary/README.md" />
        <File name="big" src="lib/socketIO_client/tests/node_modules/engine.io-parser/node_modules/has-binary/fixtures/big.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/engine.io-parser/node_modules/has-binary/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/engine.io-parser/node_modules/has-binary/package.json" />
        <File name="test" src="lib/socketIO_client/tests/node_modules/engine.io-parser/node_modules/has-binary/test.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/engine.io-parser/package.json" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/engine.io/History.md" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/engine.io/LICENSE" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/engine.io/Makefile" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/engine.io/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/engine.io/index.js" />
        <File name="engine.io" src="lib/socketIO_client/tests/node_modules/engine.io/lib/engine.io.js" />
        <File name="server" src="lib/socketIO_client/tests/node_modules/engine.io/lib/server.js" />
        <File name="socket" src="lib/socketIO_client/tests/node_modules/engine.io/lib/socket.js" />
        <File name="transport" src="lib/socketIO_client/tests/node_modules/engine.io/lib/transport.js" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/engine.io/lib/transports/index.js" />
        <File name="polling-jsonp" src="lib/socketIO_client/tests/node_modules/engine.io/lib/transports/polling-jsonp.js" />
        <File name="polling-xhr" src="lib/socketIO_client/tests/node_modules/engine.io/lib/transports/polling-xhr.js" />
        <File name="polling" src="lib/socketIO_client/tests/node_modules/engine.io/lib/transports/polling.js" />
        <File name="websocket" src="lib/socketIO_client/tests/node_modules/engine.io/lib/transports/websocket.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/engine.io/package.json" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/eventemitter3/LICENSE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/eventemitter3/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/eventemitter3/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/eventemitter3/package.json" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/has-binary/History.md" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/has-binary/LICENSE" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/has-binary/Makefile" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/has-binary/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/has-binary/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/has-binary/package.json" />
        <File name="test" src="lib/socketIO_client/tests/node_modules/has-binary/test.js" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/has-cors/History.md" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/has-cors/Makefile" />
        <File name="Readme" src="lib/socketIO_client/tests/node_modules/has-cors/Readme.md" />
        <File name="component" src="lib/socketIO_client/tests/node_modules/has-cors/component.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/has-cors/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/has-cors/package.json" />
        <File name="test" src="lib/socketIO_client/tests/node_modules/has-cors/test.js" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/http-proxy/LICENSE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/http-proxy/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/http-proxy/index.js" />
        <File name="http-proxy" src="lib/socketIO_client/tests/node_modules/http-proxy/lib/http-proxy.js" />
        <File name="common" src="lib/socketIO_client/tests/node_modules/http-proxy/lib/http-proxy/common.js" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/http-proxy/lib/http-proxy/index.js" />
        <File name="web-incoming" src="lib/socketIO_client/tests/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js" />
        <File name="web-outgoing" src="lib/socketIO_client/tests/node_modules/http-proxy/lib/http-proxy/passes/web-outgoing.js" />
        <File name="ws-incoming" src="lib/socketIO_client/tests/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/http-proxy/package.json" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/indexof/Makefile" />
        <File name="Readme" src="lib/socketIO_client/tests/node_modules/indexof/Readme.md" />
        <File name="component" src="lib/socketIO_client/tests/node_modules/indexof/component.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/indexof/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/indexof/package.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/invert-kv/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/invert-kv/package.json" />
        <File name="readme" src="lib/socketIO_client/tests/node_modules/invert-kv/readme.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/is-fullwidth-code-point/index.js" />
        <File name="license" src="lib/socketIO_client/tests/node_modules/is-fullwidth-code-point/license" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/is-fullwidth-code-point/package.json" />
        <File name="readme" src="lib/socketIO_client/tests/node_modules/is-fullwidth-code-point/readme.md" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/isarray/README.md" />
        <File name="build" src="lib/socketIO_client/tests/node_modules/isarray/build/build.js" />
        <File name="component" src="lib/socketIO_client/tests/node_modules/isarray/component.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/isarray/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/isarray/package.json" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/json3/LICENSE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/json3/README.md" />
        <File name="coverage" src="lib/socketIO_client/tests/node_modules/json3/coverage/coverage.json" />
        <File name="json3.js" src="lib/socketIO_client/tests/node_modules/json3/coverage/lcov-report/lib/json3.js.html" />
        <File name="prettify" src="lib/socketIO_client/tests/node_modules/json3/coverage/lcov-report/prettify.css" />
        <File name="prettify" src="lib/socketIO_client/tests/node_modules/json3/coverage/lcov-report/prettify.js" />
        <File name="lcov" src="lib/socketIO_client/tests/node_modules/json3/coverage/lcov.info" />
        <File name="json3" src="lib/socketIO_client/tests/node_modules/json3/lib/json3.js" />
        <File name="json3.min" src="lib/socketIO_client/tests/node_modules/json3/lib/json3.min.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/json3/package.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/lcid/index.js" />
        <File name="lcid" src="lib/socketIO_client/tests/node_modules/lcid/lcid.json" />
        <File name="license" src="lib/socketIO_client/tests/node_modules/lcid/license" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/lcid/package.json" />
        <File name="readme" src="lib/socketIO_client/tests/node_modules/lcid/readme.md" />
        <File name="HISTORY" src="lib/socketIO_client/tests/node_modules/mime-db/HISTORY.md" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/mime-db/LICENSE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/mime-db/README.md" />
        <File name="db" src="lib/socketIO_client/tests/node_modules/mime-db/db.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/mime-db/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/mime-db/package.json" />
        <File name="HISTORY" src="lib/socketIO_client/tests/node_modules/mime-types/HISTORY.md" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/mime-types/LICENSE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/mime-types/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/mime-types/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/mime-types/package.json" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/ms/History.md" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/ms/LICENSE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/ms/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/ms/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/ms/package.json" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/negotiator/LICENSE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/negotiator/README.md" />
        <File name="charset" src="lib/socketIO_client/tests/node_modules/negotiator/lib/charset.js" />
        <File name="encoding" src="lib/socketIO_client/tests/node_modules/negotiator/lib/encoding.js" />
        <File name="language" src="lib/socketIO_client/tests/node_modules/negotiator/lib/language.js" />
        <File name="mediaType" src="lib/socketIO_client/tests/node_modules/negotiator/lib/mediaType.js" />
        <File name="negotiator" src="lib/socketIO_client/tests/node_modules/negotiator/lib/negotiator.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/negotiator/package.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/number-is-nan/index.js" />
        <File name="license" src="lib/socketIO_client/tests/node_modules/number-is-nan/license" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/number-is-nan/package.json" />
        <File name="readme" src="lib/socketIO_client/tests/node_modules/number-is-nan/readme.md" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/object-component/History.md" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/object-component/Makefile" />
        <File name="Readme" src="lib/socketIO_client/tests/node_modules/object-component/Readme.md" />
        <File name="component" src="lib/socketIO_client/tests/node_modules/object-component/component.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/object-component/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/object-component/package.json" />
        <File name="object" src="lib/socketIO_client/tests/node_modules/object-component/test/object.js" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/options/Makefile" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/options/README.md" />
        <File name="options" src="lib/socketIO_client/tests/node_modules/options/lib/options.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/options/package.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/os-locale/index.js" />
        <File name="license" src="lib/socketIO_client/tests/node_modules/os-locale/license" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/os-locale/package.json" />
        <File name="readme" src="lib/socketIO_client/tests/node_modules/os-locale/readme.md" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/parsejson/Makefile" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/parsejson/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/parsejson/package.json" />
        <File name="test" src="lib/socketIO_client/tests/node_modules/parsejson/test.js" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/parseqs/Makefile" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/parseqs/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/parseqs/package.json" />
        <File name="test" src="lib/socketIO_client/tests/node_modules/parseqs/test.js" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/parseuri/History.md" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/parseuri/Makefile" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/parseuri/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/parseuri/package.json" />
        <File name="test" src="lib/socketIO_client/tests/node_modules/parseuri/test.js" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/requires-port/LICENSE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/requires-port/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/requires-port/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/requires-port/package.json" />
        <File name="test" src="lib/socketIO_client/tests/node_modules/requires-port/test.js" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/History.md" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/LICENSE" />
        <File name="Readme" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/Readme.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/index.js" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/node_modules/socket.io-parser/History.md" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/node_modules/socket.io-parser/Makefile" />
        <File name="Readme" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/node_modules/socket.io-parser/Readme.md" />
        <File name="bench" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/node_modules/socket.io-parser/bench/bench.js" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/node_modules/socket.io-parser/bench/index.js" />
        <File name="binary" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/node_modules/socket.io-parser/binary.js" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/node_modules/socket.io-parser/index.js" />
        <File name="is-buffer" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/node_modules/socket.io-parser/is-buffer.js" />
        <File name="Readme" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/node_modules/socket.io-parser/node_modules/debug/Readme.md" />
        <File name="debug" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/node_modules/socket.io-parser/node_modules/debug/debug.js" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/node_modules/socket.io-parser/node_modules/debug/index.js" />
        <File name="debug" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/node_modules/socket.io-parser/node_modules/debug/lib/debug.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/node_modules/socket.io-parser/node_modules/debug/package.json" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/node_modules/socket.io-parser/package.json" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/socket.io-adapter/package.json" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/socket.io-client/History.md" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/socket.io-client/LICENSE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/socket.io-client/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/socket.io-client/lib/index.js" />
        <File name="manager" src="lib/socketIO_client/tests/node_modules/socket.io-client/lib/manager.js" />
        <File name="on" src="lib/socketIO_client/tests/node_modules/socket.io-client/lib/on.js" />
        <File name="socket" src="lib/socketIO_client/tests/node_modules/socket.io-client/lib/socket.js" />
        <File name="url" src="lib/socketIO_client/tests/node_modules/socket.io-client/lib/url.js" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/socket.io-client/node_modules/component-emitter/History.md" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/socket.io-client/node_modules/component-emitter/LICENSE" />
        <File name="Readme" src="lib/socketIO_client/tests/node_modules/socket.io-client/node_modules/component-emitter/Readme.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/socket.io-client/node_modules/component-emitter/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/socket.io-client/node_modules/component-emitter/package.json" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/socket.io-client/package.json" />
        <File name="socket.io" src="lib/socketIO_client/tests/node_modules/socket.io-client/socket.io.js" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/socket.io-parser/History.md" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/socket.io-parser/LICENSE" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/socket.io-parser/Makefile" />
        <File name="Readme" src="lib/socketIO_client/tests/node_modules/socket.io-parser/Readme.md" />
        <File name="bench" src="lib/socketIO_client/tests/node_modules/socket.io-parser/bench/bench.js" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/socket.io-parser/bench/index.js" />
        <File name="binary" src="lib/socketIO_client/tests/node_modules/socket.io-parser/binary.js" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/socket.io-parser/index.js" />
        <File name="is-buffer" src="lib/socketIO_client/tests/node_modules/socket.io-parser/is-buffer.js" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/socket.io-parser/node_modules/json3/LICENSE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/socket.io-parser/node_modules/json3/README.md" />
        <File name="json3" src="lib/socketIO_client/tests/node_modules/socket.io-parser/node_modules/json3/lib/json3.js" />
        <File name="json3.min" src="lib/socketIO_client/tests/node_modules/socket.io-parser/node_modules/json3/lib/json3.min.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/socket.io-parser/node_modules/json3/package.json" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/socket.io-parser/package.json" />
        <File name="History" src="lib/socketIO_client/tests/node_modules/socket.io/History.md" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/socket.io/LICENSE" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/socket.io/Makefile" />
        <File name="Readme" src="lib/socketIO_client/tests/node_modules/socket.io/Readme.md" />
        <File name="client" src="lib/socketIO_client/tests/node_modules/socket.io/lib/client.js" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/socket.io/lib/index.js" />
        <File name="namespace" src="lib/socketIO_client/tests/node_modules/socket.io/lib/namespace.js" />
        <File name="socket" src="lib/socketIO_client/tests/node_modules/socket.io/lib/socket.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/socket.io/package.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/string-width/index.js" />
        <File name="license" src="lib/socketIO_client/tests/node_modules/string-width/license" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/string-width/package.json" />
        <File name="readme" src="lib/socketIO_client/tests/node_modules/string-width/readme.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/strip-ansi/index.js" />
        <File name="license" src="lib/socketIO_client/tests/node_modules/strip-ansi/license" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/strip-ansi/package.json" />
        <File name="readme" src="lib/socketIO_client/tests/node_modules/strip-ansi/readme.md" />
        <File name="LICENCE" src="lib/socketIO_client/tests/node_modules/to-array/LICENCE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/to-array/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/to-array/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/to-array/package.json" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/ultron/LICENSE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/ultron/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/ultron/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/ultron/package.json" />
        <File name="test" src="lib/socketIO_client/tests/node_modules/ultron/test.js" />
        <File name="Gruntfile" src="lib/socketIO_client/tests/node_modules/utf8/Gruntfile.js" />
        <File name="LICENSE-MIT" src="lib/socketIO_client/tests/node_modules/utf8/LICENSE-MIT.txt" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/utf8/README.md" />
        <File name="bower" src="lib/socketIO_client/tests/node_modules/utf8/bower.json" />
        <File name="component" src="lib/socketIO_client/tests/node_modules/utf8/component.json" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/utf8/package.json" />
        <File name="generate-test-data" src="lib/socketIO_client/tests/node_modules/utf8/tests/generate-test-data.py" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/utf8/tests/index.html" />
        <File name="tests" src="lib/socketIO_client/tests/node_modules/utf8/tests/tests.js" />
        <File name="utf8" src="lib/socketIO_client/tests/node_modules/utf8/utf8.js" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/window-size/LICENSE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/window-size/README.md" />
        <File name="cli" src="lib/socketIO_client/tests/node_modules/window-size/cli.js" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/window-size/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/window-size/package.json" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/wrap-ansi/index.js" />
        <File name="license" src="lib/socketIO_client/tests/node_modules/wrap-ansi/license" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/wrap-ansi/package.json" />
        <File name="readme" src="lib/socketIO_client/tests/node_modules/wrap-ansi/readme.md" />
        <File name="Makefile" src="lib/socketIO_client/tests/node_modules/ws/Makefile" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/ws/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/ws/index.js" />
        <File name="BufferPool" src="lib/socketIO_client/tests/node_modules/ws/lib/BufferPool.js" />
        <File name="BufferUtil.fallback" src="lib/socketIO_client/tests/node_modules/ws/lib/BufferUtil.fallback.js" />
        <File name="BufferUtil" src="lib/socketIO_client/tests/node_modules/ws/lib/BufferUtil.js" />
        <File name="ErrorCodes" src="lib/socketIO_client/tests/node_modules/ws/lib/ErrorCodes.js" />
        <File name="Extensions" src="lib/socketIO_client/tests/node_modules/ws/lib/Extensions.js" />
        <File name="PerMessageDeflate" src="lib/socketIO_client/tests/node_modules/ws/lib/PerMessageDeflate.js" />
        <File name="Receiver.hixie" src="lib/socketIO_client/tests/node_modules/ws/lib/Receiver.hixie.js" />
        <File name="Receiver" src="lib/socketIO_client/tests/node_modules/ws/lib/Receiver.js" />
        <File name="Sender.hixie" src="lib/socketIO_client/tests/node_modules/ws/lib/Sender.hixie.js" />
        <File name="Sender" src="lib/socketIO_client/tests/node_modules/ws/lib/Sender.js" />
        <File name="Validation.fallback" src="lib/socketIO_client/tests/node_modules/ws/lib/Validation.fallback.js" />
        <File name="Validation" src="lib/socketIO_client/tests/node_modules/ws/lib/Validation.js" />
        <File name="WebSocket" src="lib/socketIO_client/tests/node_modules/ws/lib/WebSocket.js" />
        <File name="WebSocketServer" src="lib/socketIO_client/tests/node_modules/ws/lib/WebSocketServer.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/ws/package.json" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/xmlhttprequest-ssl/LICENSE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/xmlhttprequest-ssl/README.md" />
        <File name="autotest" src="lib/socketIO_client/tests/node_modules/xmlhttprequest-ssl/autotest.watchr" />
        <File name="demo" src="lib/socketIO_client/tests/node_modules/xmlhttprequest-ssl/example/demo.js" />
        <File name="XMLHttpRequest" src="lib/socketIO_client/tests/node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/xmlhttprequest-ssl/package.json" />
        <File name="test-constants" src="lib/socketIO_client/tests/node_modules/xmlhttprequest-ssl/tests/test-constants.js" />
        <File name="test-events" src="lib/socketIO_client/tests/node_modules/xmlhttprequest-ssl/tests/test-events.js" />
        <File name="test-exceptions" src="lib/socketIO_client/tests/node_modules/xmlhttprequest-ssl/tests/test-exceptions.js" />
        <File name="test-headers" src="lib/socketIO_client/tests/node_modules/xmlhttprequest-ssl/tests/test-headers.js" />
        <File name="test-redirect-302" src="lib/socketIO_client/tests/node_modules/xmlhttprequest-ssl/tests/test-redirect-302.js" />
        <File name="test-redirect-303" src="lib/socketIO_client/tests/node_modules/xmlhttprequest-ssl/tests/test-redirect-303.js" />
        <File name="test-redirect-307" src="lib/socketIO_client/tests/node_modules/xmlhttprequest-ssl/tests/test-redirect-307.js" />
        <File name="test-request-methods" src="lib/socketIO_client/tests/node_modules/xmlhttprequest-ssl/tests/test-request-methods.js" />
        <File name="test-request-protocols" src="lib/socketIO_client/tests/node_modules/xmlhttprequest-ssl/tests/test-request-protocols.js" />
        <File name="testdata" src="lib/socketIO_client/tests/node_modules/xmlhttprequest-ssl/tests/testdata.txt" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/y18n/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/y18n/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/y18n/package.json" />
        <File name="bad-locale" src="lib/socketIO_client/tests/node_modules/y18n/test/locales/bad-locale.json" />
        <File name="en" src="lib/socketIO_client/tests/node_modules/y18n/test/locales/en.json" />
        <File name="pirate" src="lib/socketIO_client/tests/node_modules/y18n/test/locales/pirate.json" />
        <File name="y18n-test" src="lib/socketIO_client/tests/node_modules/y18n/test/y18n-test.js" />
        <File name="CHANGELOG" src="lib/socketIO_client/tests/node_modules/yargs/CHANGELOG.md" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/yargs/LICENSE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/yargs/README.md" />
        <File name="completion.sh" src="lib/socketIO_client/tests/node_modules/yargs/completion.sh.hbs" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/yargs/index.js" />
        <File name="completion" src="lib/socketIO_client/tests/node_modules/yargs/lib/completion.js" />
        <File name="parser" src="lib/socketIO_client/tests/node_modules/yargs/lib/parser.js" />
        <File name="tokenize-arg-string" src="lib/socketIO_client/tests/node_modules/yargs/lib/tokenize-arg-string.js" />
        <File name="usage" src="lib/socketIO_client/tests/node_modules/yargs/lib/usage.js" />
        <File name="validation" src="lib/socketIO_client/tests/node_modules/yargs/lib/validation.js" />
        <File name="de" src="lib/socketIO_client/tests/node_modules/yargs/locales/de.json" />
        <File name="en" src="lib/socketIO_client/tests/node_modules/yargs/locales/en.json" />
        <File name="es" src="lib/socketIO_client/tests/node_modules/yargs/locales/es.json" />
        <File name="fr" src="lib/socketIO_client/tests/node_modules/yargs/locales/fr.json" />
        <File name="id" src="lib/socketIO_client/tests/node_modules/yargs/locales/id.json" />
        <File name="ja" src="lib/socketIO_client/tests/node_modules/yargs/locales/ja.json" />
        <File name="ko" src="lib/socketIO_client/tests/node_modules/yargs/locales/ko.json" />
        <File name="nb" src="lib/socketIO_client/tests/node_modules/yargs/locales/nb.json" />
        <File name="pirate" src="lib/socketIO_client/tests/node_modules/yargs/locales/pirate.json" />
        <File name="pl" src="lib/socketIO_client/tests/node_modules/yargs/locales/pl.json" />
        <File name="pt" src="lib/socketIO_client/tests/node_modules/yargs/locales/pt.json" />
        <File name="pt_BR" src="lib/socketIO_client/tests/node_modules/yargs/locales/pt_BR.json" />
        <File name="tr" src="lib/socketIO_client/tests/node_modules/yargs/locales/tr.json" />
        <File name="zh" src="lib/socketIO_client/tests/node_modules/yargs/locales/zh.json" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/yargs/package.json" />
        <File name="LICENSE" src="lib/socketIO_client/tests/node_modules/yeast/LICENSE" />
        <File name="README" src="lib/socketIO_client/tests/node_modules/yeast/README.md" />
        <File name="index" src="lib/socketIO_client/tests/node_modules/yeast/index.js" />
        <File name="package" src="lib/socketIO_client/tests/node_modules/yeast/package.json" />
        <File name="logo-RWS" src="html/common/resources/logo-RWS.jpg" />
        <File name="flag_dun" src="html/common/modules/First_HR_Int/flag_dun.png" />
        <File name="flag_dun_old" src="html/common/modules/First_HR_Int/flag_dun_old.jpg" />
        <File name="flag_enu" src="html/common/modules/First_HR_Int/flag_enu.png" />
        <File name="flag_enu_old" src="html/common/modules/First_HR_Int/flag_enu_old.jpg" />
        <File name="hand2_with_no_tap" src="html/common/modules/First_HR_Int/hand2_with_no_tap.png" />
        <File name="hand2_with_tap" src="html/common/modules/First_HR_Int/hand2_with_tap.png" />
        <File name="style" src="html/common/modules/First_HR_Int/style.css" />
        <File name="tap2_gif" src="html/common/modules/First_HR_Int/tap2_gif.gif" />
        <File name="tap_gif" src="html/common/modules/First_HR_Int/tap_gif.gif" />
        <File name="welcome" src="html/common/modules/First_HR_Int/welcome.html" />
        <File name="buttonclick" src="html/common/css/buttonclick.css" />
        <File name="rws_goodbyeApp" src="rws_goodbyeApp.json" />
        <File name="rate" src="html/common/modules/Rate_Interaction/rate.html" />
        <File name="style" src="html/common/modules/Rate_Interaction/style.css" />
        <File name="logo-lef" src="html/common/resources/logo-lef.png" />
        <File name="twitter" src="html/common/resources/twitter.jpg" />
        <File name="ratings" src="html/ratings.html" />
        <File name="rating_service" src="rating_service.py" />
    </Resources>
    <Topics>
        <Topic name="chitchat_decos_dun" src="chitchat/chitchat_decos_dun.top" topicName="chitchat_decos" language="nl_NL" />
        <Topic name="chitchat_usg_dun" src="chitchat/chitchat_usg_dun.top" topicName="chitchat_usg" language="nl_NL" />
        <Topic name="common_chitchat_dun" src="chitchat/common_chitchat_dun.top" topicName="common_chitchat" language="nl_NL" />
        <Topic name="thanks-welcome_dun" src="thanks-welcome/thanks-welcome_dun.top" topicName="thanks-welcome" language="nl_NL" />
    </Topics>
    <IgnoredPaths />
</Package>
